"""
Report schema (Pydantic) and PDF export.
GPT-4o is forced to return JSON matching this schema —
no free-form prose, every field accounted for.
"""

from __future__ import annotations
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field
from fpdf import FPDF
import textwrap
import re


# ── Enums ──────────────────────────────────────────────────────────────────

class RiskLevel(str, Enum):
    HIGH   = "High"
    MEDIUM = "Medium"
    LOW    = "Low"
    NONE   = "None"

class Sentiment(str, Enum):
    POSITIVE = "Positive"
    NEUTRAL  = "Neutral"
    NEGATIVE = "Negative"
    MIXED    = "Mixed"


# ── Sub-models ─────────────────────────────────────────────────────────────

class CompanySnapshot(BaseModel):
    name: str
    website: Optional[str] = None
    founded: Optional[str] = None
    headquarters: Optional[str] = None
    industry: str
    size_estimate: Optional[str] = None          # e.g. "50–200 employees"
    business_description: str                    # 2–3 sentence plain-English summary

class FundingFinancials(BaseModel):
    total_raised: Optional[str] = None           # e.g. "$45M"
    last_round: Optional[str] = None             # e.g. "Series B — $20M — Jan 2023"
    known_investors: list[str] = Field(default_factory=list)
    valuation: Optional[str] = None
    revenue_signals: Optional[str] = None        # qualitative if no hard numbers
    financial_health_note: Optional[str] = None

class MarketPosition(BaseModel):
    target_market: str
    key_competitors: list[str] = Field(default_factory=list)
    differentiation: Optional[str] = None
    market_size_signal: Optional[str] = None
    competitive_moat: Optional[str] = None

class RiskFlag(BaseModel):
    category: str                                # e.g. "Legal", "Regulatory", "Reputational"
    level: RiskLevel
    description: str
    source: Optional[str] = None

class SentimentSummary(BaseModel):
    overall: Sentiment
    news_tone: Sentiment
    employee_signals: Optional[str] = None       # hiring/layoffs/glassdoor signals
    recent_headlines: list[str] = Field(default_factory=list)  # top 3–5 headlines

class ConfidenceBreakdown(BaseModel):
    score: int = Field(ge=0, le=100)             # 0–100
    data_richness: str                           # what was findable
    data_gaps: str                               # what was missing
    caveat: Optional[str] = None


# ── Master report ──────────────────────────────────────────────────────────

class DueDiligenceReport(BaseModel):
    company_snapshot:   CompanySnapshot
    business_model:     str                      # plain prose, 3–5 sentences
    funding_financials: FundingFinancials
    market_position:    MarketPosition
    risk_flags:         list[RiskFlag] = Field(default_factory=list)
    sentiment:          SentimentSummary
    confidence:         ConfidenceBreakdown
    sources:            list[str] = Field(default_factory=list)
    disclaimer: str = (
        "This report was generated by an AI agent for research purposes only. "
        "It does not constitute financial, legal, or investment advice. "
        "Always verify findings independently before making decisions."
    )


# ── JSON schema helper (fed to GPT-4o) ───────────────────────────────────

def report_json_schema() -> dict:
    return DueDiligenceReport.model_json_schema()


# ── PDF export ─────────────────────────────────────────────────────────────

def _clean(text: str) -> str:
    """Strip unicode chars FPDF can't handle."""
    return re.sub(r'[^\x00-\x7F]+', '-', text or "")

class _PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(30, 30, 46)
        self.cell(0, 10, "AI Due Diligence Report — Confidential", align="C")
        self.ln(4)
        self.set_draw_color(220, 57, 70)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} — Generated by DueDiligence Agent", align="C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(240, 240, 245)
        self.set_text_color(30, 30, 46)
        self.cell(0, 8, f"  {_clean(title)}", fill=True)
        self.ln(6)

    def body(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 60)
        for line in textwrap.wrap(_clean(text), width=95):
            self.cell(0, 6, line)
            self.ln()
        self.ln(2)

    def kv(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(80, 80, 90)
        self.cell(48, 6, _clean(key) + ":")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 60)
        self.multi_cell(0, 6, _clean(value))
        self.ln(1)

    def risk_row(self, flag: RiskFlag):
        colours = {
            RiskLevel.HIGH:   (220, 57,  70),
            RiskLevel.MEDIUM: (255, 165,  0),
            RiskLevel.LOW:    (82,  183, 136),
            RiskLevel.NONE:   (150, 150, 150),
        }
        r, g, b = colours[flag.level]
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(r, g, b)
        self.cell(28, 6, f"[{_clean(flag.level.value)}]")
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(50, 50, 60)
        self.cell(40, 6, _clean(flag.category))
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, _clean(flag.description))
        self.ln(1)


def export_pdf(report: DueDiligenceReport) -> bytes:
    pdf = _PDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 46)
    pdf.cell(0, 12, _clean(report.company_snapshot.name), align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(120, 120, 130)
    pdf.cell(0, 8, "Due Diligence Report", align="C")
    pdf.ln(10)

    # Confidence badge
    score = report.confidence.score
    pdf.set_font("Helvetica", "B", 13)
    colour = (82, 183, 136) if score >= 70 else (255, 165, 0) if score >= 40 else (220, 57, 70)
    pdf.set_text_color(*colour)
    pdf.cell(0, 8, f"Confidence Score: {score}/100", align="C")
    pdf.ln(10)

    # 1. Snapshot
    s = report.company_snapshot
    pdf.section_title("1. Company Snapshot")
    if s.founded:       pdf.kv("Founded",     s.founded)
    if s.headquarters:  pdf.kv("HQ",          s.headquarters)
    pdf.kv("Industry",  s.industry)
    if s.size_estimate: pdf.kv("Size",         s.size_estimate)
    if s.website:       pdf.kv("Website",      s.website)
    pdf.body(s.business_description)

    # 2. Business model
    pdf.section_title("2. Business Model")
    pdf.body(report.business_model)

    # 3. Funding
    f = report.funding_financials
    pdf.section_title("3. Funding & Financials")
    if f.total_raised:        pdf.kv("Total Raised",  f.total_raised)
    if f.last_round:          pdf.kv("Last Round",     f.last_round)
    if f.valuation:           pdf.kv("Valuation",      f.valuation)
    if f.known_investors:     pdf.kv("Investors",      ", ".join(f.known_investors))
    if f.revenue_signals:     pdf.kv("Revenue Signals",f.revenue_signals)
    if f.financial_health_note: pdf.body(f.financial_health_note)

    # 4. Market position
    m = report.market_position
    pdf.section_title("4. Market Position")
    pdf.kv("Target Market",   m.target_market)
    if m.key_competitors:     pdf.kv("Competitors",    ", ".join(m.key_competitors))
    if m.differentiation:     pdf.kv("Differentiation",m.differentiation)
    if m.competitive_moat:    pdf.kv("Moat",           m.competitive_moat)
    if m.market_size_signal:  pdf.kv("Market Size",    m.market_size_signal)

    # 5. Risk flags
    pdf.section_title("5. Risk Flags")
    if report.risk_flags:
        for flag in report.risk_flags:
            pdf.risk_row(flag)
    else:
        pdf.body("No significant risk flags identified.")

    # 6. Sentiment
    sent = report.sentiment
    pdf.section_title("6. Sentiment & News")
    pdf.kv("Overall Sentiment", sent.overall.value)
    pdf.kv("News Tone",         sent.news_tone.value)
    if sent.employee_signals:   pdf.kv("Employee Signals", sent.employee_signals)
    if sent.recent_headlines:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(80, 80, 90)
        pdf.cell(0, 6, "Recent Headlines:")
        pdf.ln(4)
        for h in sent.recent_headlines:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 60)
            pdf.cell(6, 6, "-")
            pdf.multi_cell(0, 6, _clean(h))

    # 7. Confidence
    pdf.section_title("7. Confidence Breakdown")
    pdf.kv("Score",       f"{report.confidence.score}/100")
    pdf.kv("Data Found",  report.confidence.data_richness)
    pdf.kv("Data Gaps",   report.confidence.data_gaps)
    if report.confidence.caveat: pdf.body(report.confidence.caveat)

    # 8. Sources
    if report.sources:
        pdf.section_title("8. Sources")
        for src in report.sources:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 120, 200)
            pdf.cell(0, 5, _clean(src))
            pdf.ln()

    # Disclaimer
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, _clean(report.disclaimer))

    return bytes(pdf.output())
